name: Build and Deploy Packages

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@master
      id: nbgv        
      
    # Build and deploy nuget package
    - name: Build & Deploy Package
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/mendix/index.json" -UserName MarcellVanRooyen -Password ${{ secrets.GHPACKAGESTOKEN }}
        dotnet build -c Release
        copy .\bin\LibGit2Sharp\Release\*.* .\nuget.package\lib -Recurse -Force
        nuget pack .\nuget.package\Mendix_package.nuspec  -Version 1.101.3 -NoPackageAnalysis
        nuget push **/Mendix.LibGit2Sharp*.nupkg -Source "GitHub" -SkipDuplicate
      shell: powershell
    
     
